name: responsive_portfolio_ui
description: Responsive portfolio UI with Flutter

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.2
  auto_route: ^3.2.4
  flutter_svg: ^1.0.3
  google_fonts: ^2.3.1
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0
  auto_route_generator: ^3.2.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/svg/
    - assets/images/png/
